### PR TITLE
Updated ResXFileCodeGeneratorEx to work with Visual Studio version 2019 (Preview)

### PR DESCRIPTION
**Pull request by stefanlenselink**

### CODE REVIEW

**Comment by dave-q** [comment]
Any movement on this?

**Comment by cpaton** [comment]
Closing this pull request as all changes have been incorporated into a later request from marknadig which includes these changes too

**Comment by freica** [comment]
Is there a chance to get it run for VS 2022?

**Comment by stefanlenselink** [comment]
> Is there a chance to get it run for VS 2022?

What about https://github.com/cpaton/ResXFileCodeGeneratorEx/pull/3 ?

**Pull request closed without merging**
